---
# defaults file for tomcat-ansible-role

tomcat_state: present

tomcat_version: 8.5.42
tomcat_major_version: "{{ tomcat_version.split('.')[0].tomcat_version.split('.')[1] }}"

tomcat_install_java: True
tomcat_java_version: 1.8
tomcat_java_home: /usr/lib/jvm/jre

tomcat_java_packages_EL:
 - {package: "java-{{ tomcat_java_version }}{% if '1.' in tomcat_java_version|string %}.0{% endif %}-openjdk"}

tomcat_downloadURL: https://archive.apache.org/dist

tomcat_user: tomcat
tomcat_group: tomcat

tomcat_install_path: /opt
tomcat_service_name: tomcat
tomcat_systemd_config_path: /etc/systemd/system
tomcat_jvm_memory_percentage_xms: 15
tomcat_jvm_memory_percentage_xmx: 55

tomcat_permissions_production: False
tomcat_permissions_ensure_on_every_run: True


tomcat_users: []

tomcat_user_roles: []

tomcat_temp_download_path: /tmp/ansibletomcattempdir

# Switch to true if upgrading from role release 1.3.2 or previous in order
# to remove /usr/lib/systemd/system/{{ tomcat_service_name }}.service
tomcat_delete_old_systemd_service_file: False

# Disconnected remote parameters
tomcat_remote_is_disconnected: False

