---
- name:                    Tomcat - Installation
  hosts:                   tomcat_servers
  become:                  true
  vars:
    tomcat_version: 8.5.23
    
    tomcat_permissions_production: True
    
  roles:
    - roles/tomcat-install

