---
# defaults file for tomcat-ansible-role

tomcat_state: present

tomcat_version: 8.5.42

tomcat_java_home: /usr/lib/jvm/jre

tomcat_java_packages_EL:
 - {package: "java-{{ tomcat_java_version }}{% if '1.' in tomcat_java_version|string %}.0{% endif %}-openjdk"}


tomcat_user: tomcat
tomcat_group: tomcat

tomcat_install_path: /opt
tomcat_service_name: tomcat
tomcat_systemd_config_path: /etc/systemd/system

tomcat_users: []

tomcat_user_roles: []



# Switch to true if upgrading from role release 1.3.2 or previous in order
# to remove /usr/lib/systemd/system/{{ tomcat_service_name }}.service
tomcat_delete_old_systemd_service_file: False

# Disconnected remote parameters
tomcat_remote_is_disconnected: False

# Uninstall default parameters
tomcat_uninstall_create_backup: True

tomcat_uninstall_remove_user: True
tomcat_uninstall_remove_group: True
tomcat_uninstall_remove_java: False

tomcat_uninstall_remove_all: False
